title: Studio B
baseURL: /
params:
  description: Engineering and Programming Blog
  layout_style: overflow
  palette: orange
  header:
    type: header
    template: header
    title: Studio B
    tagline: An Engineering and Programming Blog
    profile_img: images/avatar.png
    profile_img_alt: Author avatar
    background: dark
    has_nav: true
    nav_links:
      - type: action
        template: action
        label: Home
        url: /
        style: link
      - type: action
        template: action
        label: Blog
        url: /blog/
        style: link
      - type: action
        template: action
        label: 100DaysofCode
        url: /code-100/
        style: link
      - type: action
        template: action
        label: About
        url: /about/
        style: link
      - type: action
        template: action
        label: Contact
        url: /contact/
        style: link
    has_social: true
    social_links:
      - type: action
        template: action
        label: Twitter
        url: 'https://twitter.com/chelly_242'
        style: icon
        icon_class: fa-twitter
        new_window: true
      - type: action
        template: action
        label: Instagram
        url: 'https://www.instagram.com/studiob_squared/'
        style: icon
        icon_class: fa-instagram
        new_window: true
      - type: action
        template: action
        label: GitHub
        url: 'https://github.com/chelly242'
        style: icon
        icon_class: fa-github
        new_window: true
  footer:
    type: footer
    template: footer
    content: >-
      &copy; Studio B. All rights reserved. This Jamstack site was created with love and 
      <a href="https://www.stackbit.com/?utm_source=deployed-footer"
      target="_blank" rel="noopener">Stackbit</a>.
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
