---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: https://api.stackbit.com/project/6017171afaecfb0016ac94a0/webhook/forestry
sections:
- type: document
  path: config.yaml
  label: Site Configuration
  templates:
  - config
- type: document
  path: content/blog/_index.md
  label: Blog
  templates:
  - blog
- type: directory
  path: content
  label: Pages
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - advanced
  - page
  - post
upload_dir: home/assets
public_path: CLOUDINARY_URL=cloudinary://428426985648642:G6iniFRROEJgYal0G0bo-OLiYrI@studio-b
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.47
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.80.0
